version: '3.5'

services:
  app:
    container_name: football-manager-app
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      FPM_USER: www
      FPM_GROUP: www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
      - proxy-network

  nginx:
    container_name: football-manager-nginx
    image: nginx:1.18.0
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
      - proxy-network
    environment:
      - NGINX_PORT=${NGINX_PORT}
    command: /bin/bash -c "envsubst '$${NGINX_PORT}' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf && nginx -g 'daemon off;'"

  db:
    image: mysql:latest
    ports:
      - "33069:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
        test: "mysqladmin ping -h localhost"
        interval: 1s
        timeout: 1s
        retries: 60
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "15674:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  proxy-network:
    driver: bridge
    external: true